// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3R5Pf1b5asshVgCt964RKyFkBYIMJM8M',
    appId: '1:658057817205:web:d689b69a7767d6f09a1c3c',
    messagingSenderId: '658057817205',
    projectId: 'school-management-112',
    authDomain: 'school-management-112.firebaseapp.com',
    storageBucket: 'school-management-112.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB69F8uaL13Jr6bRR25Te-DgJuuj41Lio',
    appId: '1:658057817205:android:439420011ac0ea2a9a1c3c',
    messagingSenderId: '658057817205',
    projectId: 'school-management-112',
    storageBucket: 'school-management-112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ByAE_6XsfB83cO_ZUzkDtKigaJD88ys',
    appId: '1:658057817205:ios:c744918199f545739a1c3c',
    messagingSenderId: '658057817205',
    projectId: 'school-management-112',
    storageBucket: 'school-management-112.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ByAE_6XsfB83cO_ZUzkDtKigaJD88ys',
    appId: '1:658057817205:ios:c744918199f545739a1c3c',
    messagingSenderId: '658057817205',
    projectId: 'school-management-112',
    storageBucket: 'school-management-112.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3R5Pf1b5asshVgCt964RKyFkBYIMJM8M',
    appId: '1:658057817205:web:cba10b82c0a968099a1c3c',
    messagingSenderId: '658057817205',
    projectId: 'school-management-112',
    authDomain: 'school-management-112.firebaseapp.com',
    storageBucket: 'school-management-112.firebasestorage.app',
  );
}
